table Locations
	lineageTag: 28517119-6398-469a-a219-ee3a4824e4c7

	column Location
		dataType: string
		lineageTag: ce1f3184-f47d-41f5-98ba-c82fa0a64621
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column LocationKey
		dataType: int64
		formatString: 0
		lineageTag: 92101653-7f7e-4595-b4ea-7ea7a4debde0
		summarizeBy: none
		sourceColumn: LocationKey

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: cd118908-c825-4c1d-99ec-29dc22d08ab6
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 6d7506b6-9e39-4a1e-baea-9d3a06747058
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 85834ffb-83c9-44d1-95f6-6412c62d7edc
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Locations = m
		mode: import
		queryGroup: Final
		source =
				let
				    Source = List.Distinct( List.Combine( {CleanedData[Pickup Location], CleanedData[Pickup Location]}) ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Added Index" = Table.AddIndexColumn(#"Converted to Table", "LocationKey", 0, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Column1", "Location"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Location"}, #"Location-Region-Latitude-Longitude", {"Location"}, "Location-Region-Latitude-Longitude", JoinKind.LeftOuter),
				    #"Expanded Location-Region-Latitude-Longitude" = Table.ExpandTableColumn(#"Merged Queries", "Location-Region-Latitude-Longitude", {"Region", "Latitude", "Longitude"}, {"Region", "Latitude", "Longitude"})
				in
				    #"Expanded Location-Region-Latitude-Longitude"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

